/* eslint-disable @typescript-eslint/no-empty-interface */
// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
  SMARTSUITE_API_TOKEN: string;
  SMARTSUITE_WORKSPACE_ID: string;
  SMARTSUITE_BASE_URL?: string;
  SMARTSUITE_STATUS_IN_STOCK_VALUE?: string;
}
